name: Build Phoenix iCal
on:
  schedule:
    - cron: "7 5 * * *"  # daily 05:07 Europe/London
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 icalendar
      - name: Build calendar
        run: python build_calendar.py phoenix.ics
        timeout-minutes: 10
        continue-on-error: false
      - name: Commit and push if changed
        run: |
          git config user.name "phoenix-ical-bot"
          git config user.email "actions@users.noreply.github.com"
          
          # Check if there are any changes to phoenix.ics
          if git diff --quiet phoenix.ics; then
            echo "No changes to phoenix.ics - skipping commit and push"
          else
            echo "Changes detected in phoenix.ics - committing and pushing"
            git add phoenix.ics
            git commit -m "Update phoenix.ics"
            
            # Try to pull and rebase, with retry logic
            echo "Pulling latest changes before push..."
            if ! git pull --rebase origin main; then
              echo "Rebase failed, trying to reset and pull again..."
              git rebase --abort || true
              git reset --hard HEAD~1
              git pull origin main
              git add phoenix.ics
              git commit -m "Update phoenix.ics"
            fi
            
            echo "Pushing changes..."
            git push
          fi